### ISSUE TITLE
Finish the Park interface

### ISSUE THREAD

**Issue by atrievel** [atrievel/NationalParkViewer#1]
### Summary
Finish the Park interface by adding the fields/interfaces marked TODO. You may need to create several other interfaces to accurately represent the data model (example: the ```operatingHours``` field has ```standardHours``` and ```exceptions```, which will all need to be their own interfaces).

### Where to start
[Review the model here](https://www.nps.gov/subjects/developer/api-documentation.htm#/) under the Models/Parks section at the bottom of the page. Then, create the additional interfaces needed to complete the Park interface.

### Expectations
Here is a list of interfaces that need to be created and then implemented inside the Parks interface, located at `./src/app/modles/Park.ts`:
* activities
* addresses
* contacts
* entranceFees
* entrancePasses
* images
* operatingHours

Feel free to reach out with any questions and I will respond ASAP

**Comment by NikoDyring** [comment]
Hi. I'd love to give this a go. Can you assign me? 👍

**Comment by atrievel** [comment]
@NikoDyring - thanks, I’ll assign you and look at the PR in a bit

**Comment by NikoDyring** [comment]
Thanks @atrievel 😎
