### ISSUE TITLE
Finish the ThingsToDo interface

### ISSUE THREAD

**Issue by atrievel** [atrievel/NationalParkViewer#2]
### Summary
Finish the Park interface by adding the fields/interfaces marked TODO. You may need to create several other interfaces to accurately represent the data model.

### Where to start
[Review the model here](https://www.nps.gov/subjects/developer/api-documentation.htm#/) under the Models/ThingsToDo section at the bottom of the page. Then, create the additional interfaces needed to complete the ThingsToDo interface.

### Expectations
Here is a list of interfaces that need to be created and then implemented inside the Parks interface, located at `./src/app/modles/ThingsToDo.ts`:
* relatedParks
* images
* activities
* topics

Feel free to reach out with any questions and I will respond ASAP

**Comment by thomaslian** [comment]
Hi! I'll do this! :)

**Comment by atrievel** [comment]
@thomaslian - thanks, you got it!
